spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
        
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${rabbitmq.username:guest}
    password: ${rabbitmq.password:guest}

eureka:
  client:
    register-with-eureka: true         # This service registers itself with the Eureka server
    fetch-registry: true               # This service fetches the list of other services from Eureka
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka} # The Eureka server URL

  instance:
    prefer-ip-address: true            # Use the IP address instead of hostname when registering

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}  # Zipkin collector endpoint

  tracing:
    sampling:
      probability: 1.0                 # Always sample traces (100% of requests)
