server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 5 # Number of calls used to calculate the failure rate
        failureRateThreshold: 50 # Circuit opens if 50% of the last calls failed
        waitDurationInOpenState: 10s # Time the circuit stays open before switching to half-open
        
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        
    circuitbreaker:
      resilience4j:
        enabled: true
        
    stream:
      default-binder: rabbit
      bindings:
        order-out-0:
          destination: orders
          content-type: application/json
          
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${rabbitmq.username:guest}
    password: ${rabbitmq.password:guest}

custom:
  message: "Welcome to the Order Service!"
