server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: ${db.username}
    password: ${db.password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true
    
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      
  tracing:
    sampling:
      probability:  1.0    