server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

custom:
  message: "Welcome to the Product Service!"