server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: ${db.username}
    password: ${db.password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

custom:
<<<<<<< HEAD
  message: "Welcome to the Product Service"
=======
  message: "Welcome to the"
>>>>>>> 14ccb9f03dcee40ce018f7c31593a70099c53c90
